-- list of nodes preconfigured at boot time
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'tb3_1');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'tb3_2');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'tb3_3');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'tb3_4');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'tb3_5');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'tb3_6');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'tb3_7');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'tb3_8');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'tb3_9');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'tb3_10');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'tb3_11');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'tb3_12');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'tb3_13');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'tb3_14');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'tb3_15');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'tb3_16');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'tb3_17');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'tb3_18');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'tb3_19');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'tb3_20');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'cr3_1');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'cr3_2');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'cr3_3');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'cr3_4');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'cr3_5');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'cr3_6');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'cr3_7');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'cr3_8');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'cr3_9');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'cr3_10');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'cr3_11');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'cr3_12');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'cr3_13');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'cr3_14');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'cr3_15');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'cr3_16');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'cr3_17');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'cr3_18');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'cr3_19');
INSERT INTO NODES (id, name) VALUES (SEQ_NODE.nextval, 'cr3_20');

-- list of wearables preconfigured at boot time
INSERT INTO WEARABLES (id, code, description) VALUES (SEQ_WEARABLE.nextval, 'wb_1', 'paziente 1');
INSERT INTO WEARABLES (id, code, description) VALUES (SEQ_WEARABLE.nextval, 'wb_2', 'paziente 2');
INSERT INTO WEARABLES (id, code, description) VALUES (SEQ_WEARABLE.nextval, 'wb_3', 'paziente 3');
INSERT INTO WEARABLES (id, code, description) VALUES (SEQ_WEARABLE.nextval, 'wb_4', 'paziente 4');
INSERT INTO WEARABLES (id, code, description) VALUES (SEQ_WEARABLE.nextval, 'wb_5', 'paziente 5');
INSERT INTO WEARABLES (id, code, description)  VALUES (SEQ_WEARABLE.nextval, 'wb_6', 'paziente 6');
INSERT INTO WEARABLES (id, code, description)  VALUES (SEQ_WEARABLE.nextval, 'wb_7', 'paziente 7');
INSERT INTO WEARABLES (id, code, description)  VALUES (SEQ_WEARABLE.nextval, 'wb_8', 'paziente 8');
INSERT INTO WEARABLES (id, code, description)  VALUES (SEQ_WEARABLE.nextval, 'wb_9', 'paziente 9');
INSERT INTO WEARABLES (id, code, description)  VALUES (SEQ_WEARABLE.nextval, 'wb_10', 'paziente 10');